### ISSUE TITLE
request date form improvement

### ISSUE THREAD

**Issue by dreamingmind** [dreamingmind/bindery#154]
If a user is logged in their email will be available (it's required registration data). In this case, the request date form on Workshop upcoming should have the email field auto-filled.

**Comment by curlyjason** [comment]
Got it set (using default), but cannot figure out the variable or object 
or pull the useremail from.

Jason

Don Drake wrote:

**Comment by dreamingmind** [comment]
There are a bunch of user values set in appController beforeFilter(). The $userdata array has an 'email' element.

But for some reason Workshop controller is doesn't seem to be running the appController beforeFilter() properly. It looks like it's set up properly but non of the user info is getting set. You can see by logging in and going to the workshop page. There you'll see the page says you're not logged in!

Workshop has a beforeFilter and seems to be calling it's parents filter....

**Comment by dreamingmind** [comment]
I've verified the beforeFilter is running in both workshop and appcontroller. But the userdata array is not getting set when workshop controller makes the call. Some failure with the Auth component in this case? very strange and localized.

**Comment by dreamingmind** [comment]
Ok. 

In appController line 133 failing
<code>
        if ($this->Auth->user() != null) {
</code>

As a result, the $userdata array is not being set. But this only seems to be happening on Workshop.
This line depends on the Session being active and that is also managed by appController and works everywhere else.

**Comment by curlyjason** [comment]
I'll take a look at the code.

Don Drake wrote:

**Comment by dreamingmind** [comment]
It seems to me the failure of Auth->user() got fixed. That was a white-space error in one of the files.

So, now the email should be auto populating?

I'm going to try Session-izing the visitors email if they provide it and they are not otherwise logged in or registered. That way, if they give an email in this workshop form and later, during the same session, go to spec a product, their email will be available for that form too.

I think I'll have some app_controller method to do the checking. I'm not sure how it will get called. First thought on [issue #161](161)

**Comment by curlyjason** [comment]
I totally agree that we should default the user email. In fact, I think it's in $this->useremail no matter where you are (part of the appcontroller), However, that box doesn't show up on the detail pages, so I have to debug that first.

**Comment by curlyjason** [comment]
Done
