### ISSUE TITLE
automatic email sessionization

### ISSUE THREAD

**Issue by dreamingmind** [dreamingmind/bindery#161]
An idea for app_controller:

When a user is not logged in and does not have a session with their email, look to see if the current activity is a POST. If it is, check the data array for an email field. If one is found, sessionize it.

**Comment by curlyjason** [comment]
Here I'm just not sure how to define/use Session. I have to do some reading.

Jason

**Comment by dreamingmind** [comment]
it's actually a small and easy to use component(?).

I already use it to remember search strings in some admin/image import pages

http://book.cakephp.org/1.3/en/The-Manual/Core-Components/Sessions.html
