### ISSUE TITLE
Image is doubling?? in workshop/detail.ctp

### ISSUE THREAD

**Issue by curlyjason** [dreamingmind/bindery#162]
The main image on detail.ctp is not displaying correctly.

**Comment by curlyjason** [comment]
happening on upcoming.ctp, too. Not sure if the fade image is just not properly aligned

**Comment by dreamingmind** [comment]
If you firebug the correct and incorrect pages you'll probably see that the parent element on the good page is setting some stuff. Wrapping the other page to match should fix it.

**Comment by curlyjason** [comment]
fixing the open form fixed the css
