### ISSUE TITLE
Wouldn't it be nice to have an actual Data Entry/Data Edit plan?

### ISSUE THREAD

**Issue by dreamingmind** [dreamingmind/bindery#17]
This would tell me what forms to put on what pages.

**Comment by curlyjason** [comment]
Wha?

**Comment by dreamingmind** [comment]
Tentative plan: Make found sets persistent and portable. Then the admin can move between various specialized pages with a record or records and get the required tasks done.

This will allow some organic growth to the site. Possibly not a good long term solution but it should work fine in the short/medium term as long as the admin page links are widely accessible and the found-record structure is compatible with the various editing pages.

**Comment by dreamingmind** [comment]
this is a stupid and vague issue
