### ISSUE TITLE
The new Design model and the shopping cart

### ISSUE THREAD

**Issue by dreamingmind** [dreamingmind/bindery#187]
The new Design model was written to store product design specs. This storage could provide the basis for:
- saved customer orders
- Buy buttons on gallery and blog pages throughout the site to smooth out the difficulty of navigating and spec'ing purchases.

But, how about Edition purchases? And how will the proposed Buy buttons be included on the pages?

The Supplement model was created to attach arbitrary data to any display page through ContentCollection links (currently only used on Gallery). My first thought when looking for a place to store product spec's was to put them in Supplement. But I chose the new model, Design.

Supplement may still serve as a way to carry Design record link data to the content records. Then Design links could be created that would be available on any page with Content records.
- the supplement links could be shown with the content record that carries it
- or accumulated from all content on the page and shown in a common location

Some value in the Design table could guide the link construction so a proper destination page is targeted. 
- For product specs, this would be the proper catalog-purchase page so the user could fine-tune the specs. 
- For Editions this could be some kind of prospectus page or might go directly to the shopping cart
- For Seconds (unsold items off my shelf) this would probably be a direct shopping cart call.

Since some are proposed as in-site links and others as cart calls, the data requirements will be very different. But the Design table is made to hold serialized array data so any form data could be stored. As long a there was a key to what decoded data should be expected, all will be well.

It would be possible to include the key data in the serialized array. In this case:
- A universal storage routine would append key data to the form data array
- A universal retrieval routine would separate the key and form data and pass it back to the calling action

This process would cut down on new field creation in Design as the site needs change.

**Comment by curlyjason** [comment]
Holy Shit, I read this and it made sense!!!

The top-down sense here allowed you to drill down the the local primitive, the universal storage and retrieval routines and the basic ways they'll interact with the data set.
