### ISSUE TITLE
should qty 0 leave the item on the cart or delete it?

### ISSUE THREAD

**Issue by dreamingmind** [dreamingmind/bindery#210]
leaving means you can postpone purchase but not have to re-spec. 

but how will the cart persist if some items are purchased and others are zero?

possibly they will just go into history for reorder? That might be simplest but possibly confusing.

**Comment by curlyjason** [comment]
I'm not sure what you mean by 'purchased' items. If a cart has some items at zero quantity, and the user clicks 'buy now', then the system should ask how many of the zero quantity items they would like to purchase, with an obvious highlight of the item, the quantity and the remove button. Take a moment to allow them to spend more money if there is any way to think they might want to spend more. Fairly non-intrusive?

**Comment by dreamingmind** [comment]
These were some thoughts about how to get a 'wish list' feature for free.

I'm blowing it off for now and just killing items that go to zero.
