### ISSUE TITLE
Make a wish list

### ISSUE THREAD

**Issue by dreamingmind** [dreamingmind/bindery#211]
Transfer cart items to some other table. 

What about non-logged in users?

**Comment by curlyjason** [comment]
non-logged users can't have a wish list, I think that's reasonable.
I don't think we need to transfer to another table. Just a new type in the same table??
     - But, I am getting sick of types in tables. Why am I so afraid of more tables?

**Comment by dreamingmind** [comment]
Well, for one thing, it doesn't feel dry. But on the other hand it reduces cohesion and increases coupling.

So it is a trade off.
