### ISSUE TITLE
contact/address js data synchronization is not working right

### ISSUE THREAD

**Issue by dreamingmind** [dreamingmind/bindery#274]
This is on the first checkout page that gets addresses.

The second address always appears. If empty it should set to mirror first. If matching it should hide.

The name should copy to the first address (and potentially to the second).

Something is not getting set in the second address when it matches. because entering the first and submitting emits a mysterious fill-out-field prompt and prevents you from advancing.

**Comment by curlyjason** [comment]
Is it possible that there's a required field that's not being set?

....................
Jason

**Comment by dreamingmind** [comment]
That's probably true. If I toggle the 'match' checkbox, it will snap into place.

But this whole page is a candidate for the mediator pattern. Wikipedia is okay on the topic, but the design pattern book is right on the mark for what I'd like to have here.

But I've never looked at design patterns in a js program.

I may just tweak this page (which is close to operational) rather than refactor it.

**Comment by dreamingmind** [comment]
That's probably true. If I toggle the 'match' checkbox, it will snap into place.

But this whole page is a candidate for the mediator pattern. Wikipedia is okay on the topic, but the design pattern book is right on the mark for what I'd like to have here.

But I've never looked at design patterns in a js program.

I may just tweak this page (which is close to operational) rather than refactor it.
