### ISSUE TITLE
Create Workshop Property: current_workshop

### ISSUE THREAD

**Issue by dreamingmind** [dreamingmind/bindery#51]
another useful property of Workshop would be current_workshop. A query, probably looking at first_day and last_day of Session.

**Comment by curlyjason** [comment]
First programming!

**Comment by dreamingmind** [comment]
Here is the Workshop Model documentation page which was generated from the comments on that page (as it exists on my machine). You can see how the comments turn into the documentation! Sweet!

...Well, the attachment doesn't come through. I would have been surprised if it did.

Don Drake
Dreaming Mind

ddrake@dreamingmind.com
IM: stitchbyhand
http://www.dreamingmind.com
http://workshops.dreamingmind.com
(510) 537-9711
